### PR TITLE
Added support for Z-wave Led driver.

### PR DESCRIPTION
**Pull request by hfaas**
Added support for [LED DRIVER Z-WAVE 12/36V 720W ROBB SMARRT](https://www.robbshop.nl/led-driver-z-wave-12-36v-720w-robb-smarrt?sqr=led%20driver&)

Currently all 4 channels are handled as single channel (device doesn't seem to be a MultiChannelNode supported device), so I'm figuring out whether it could be possible to control the different outputs separately.

### CODE REVIEW

**Comment by TedTolboom** [comment]
@hfaas thanks for the contribution.
As I interpretate the LED driver, it has only one controllable dimmer, but power is distributed over 4 channels. So if you connect 4 led strings, the brightness is equally distributed. 

Compared to connecting the same led stings serial to one another, the brightness will decrease over it's length.

But I'll check anyway.

**Comment by hfaas** [comment]
@TedTolboom I have been in contact with Robshop and it seems like you are right.
I was confused by the way it was described in manual and on the device it self. There might be a nasty "hacky" way to do it by setting it up as a RGBW driver (at least if it accepts the paramter to be set like that) and mis-use those "channels" for it.

But that will be just playing around with it in a matter that is not really intended.

Anyway I will change some naming (4 channel stuff) to make it less confusing, but other then that I think this pull request will then contain all that is needed. 
I would like your opinion though, about the "stage" parameter and naming. Since I found it quite confusing terminology. 
It is used for when the device is switched on, it can do some "funny" stuff like fading in and out or flash on and off a number of times (I don't see a purpose for it, but that is a different story). Anyway the naming "stage" is in my opinion confusing, so I'm not sure whether it should stay there or should be called differently?

Is there anything else that you want me to update/change before pulling it in?

**Comment by TedTolboom** [comment]
Thanks for the update...
I'll merge the PR into a dedicated branch and work from there...

Likely, I will change the driver ID, so I can use a naming convention for the different devices:
ie. `ZW_LED-dimmer_white`, `ZW_LED-dimmer_RGB`, `ZW_LED-driver_white` and `ZB_LED-dimmer_white`

I'll first check if the `LED-dimmer` and `LED-driver` actually have different implementations, otherwise I can merge them as well..

**Comment by hfaas** [comment]
Your welcome, if you need anything from me, let me know.

**Pull request merged**
